version: '3.4'

x-template: &flyway-template
  image: flyway/flyway:latest
  volumes:
    - ./db/sql:/flyway/sql # マイグレーション用SQLファイルの格納先
    - ./db/conf:/flyway/conf # 設定ファイルの格納先
  depends_on:
    - db

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

#  sonarqube:
#    image: sonarqube:9.7.0-community
#    platform: linux/amd64
#    ports:
#      - 9000:9000

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - 8090:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  db:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  db-store: