# DB????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatistrysample
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#????????
logging:
  level:
    web: trace